pub mod ast;
pub mod ast_lowering;
mod ast_visit;
pub mod hir;
pub mod item_collect;
pub mod parsing;
pub mod resolution;
pub(super) mod thir;
pub mod thir_build;
pub(super) mod ty_infer;
pub(super) mod ty_lower;
pub mod typecheck;
